### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Validark** [Validark/DynSDT#2]
## Demo
- [x] Make transition from Completion Trie to decomposed trie animate the vertical linked lists into the parent nodes 
- [ ] Dark mode
- [ ] Shift the Completion Trie and subsequent diagrams upwards slightly by default?

## Paper
- [ ] Fix font inconsistency across platforms
    - [x] Currently, Figures 1-3 use the "serif" font-family, which becomes the default serif font on whatever the target platform is. For consistency, a dynamically loaded font should be used or the text should be converted to paths.
        - At present, I'd prefer a dynamically loaded font
    - [ ] Change the Big-Theta from Georgia to a dynamically loaded font 
    - [ ] Consider moving all diagrams to monospace or the KaTeX_Main font?
- [ ] Where $\large n$ and $\large bp[i]$ are identical, we should remove $\large n$ in favor of $\large bp[i]$
- [ ] Add an "Experimental Analysis" section
    - [ ] The main problem I have with this is that performance characteristics may vary by implementation. Maybe I will support an analysis for each of them, but without scripts only one will be shown? 
    - [ ] Decide: Should I have a performance comparison with an implementation of the Completion Trie? Just horizontally sorted or should I include the totally unsorted Completion Trie as well?
    - [ ] Diagrams I am thinking to include:
        - [ ] How $\large k$ correlates with runtime
            - This will only use those prefix queries which are in the top-10 or top-100 of number of total completions in the entire dataset
        - [ ] How number of completions to a query (for all possible prefix string queries) correlates with runtime (when $\large k$ is set to 10)
- [ ] Submit to some academic platforms

## Code
- [ ] Add implementations!
    - #### I am open to Pull Requests from others for more implementations!
    - [ ] [<sub><sub><img src="https://upload.wikimedia.org/wikipedia/commons/0/0d/C_Sharp_wordmark.svg" alt="C-sharp" height="22"></sub></sub>](https://docs.microsoft.com/en-us/dotnet/csharp/) This was the original version!
        - [ ] Add tests
        - [x] Upload graphs (and code that generates them) for experimental analysis
        - [x] #3
            - Previously, the maximum size was allocated https://github.com/Validark/DynSDT/blob/4997b24f759bb8e551159d030240cded3aa4dd74/c%23/PruningRadixTrie/PruningRadixTrie.cs#L906
    - [x] [<sub><sub><img src="https://upload.wikimedia.org/wikipedia/commons/4/4c/Typescript_logo_2020.svg" alt="TypeScript" height="22"></sub></sub>](https://www.typescriptlang.org/) The initial implementation only exists to closely match the pseudocode in the paper, and the pseudocode was actually based on the C# version. The problem with the direct port is that the C# version wraps nodes in **tuples**, which are **values**, not actual objects with lifetimes. However, in TS/JS, there is no such concept, just objects. Hence, the TS version should have the LCP values moved into the node that it actually describes, to cut the number of JS objects in half.
     - [ ] [<sub><sub><img src="https://upload.wikimedia.org/wikipedia/commons/c/cf/Lua-Logo.svg" alt="Lua" height="22"></sub></sub>](https://www.lua.org/) Should be pretty easy to port from TypeScript, especially given my extensive experience developing https://roblox-ts.com/. Could probably be largely auto-generated.
     - [ ] [<sub><sub><img src="https://raw.githubusercontent.com/viruzvz/logos-svg/master/java.svg" alt="Java" height="22"></sub></sub>](https://www.java.com/) Should be pretty similar to C#, right?
     - [x] [<sub><sub><img src="https://raw.githubusercontent.com/Validark/Validark/master/zig-z.svg" alt="Zig" height="22"></sub></sub>](https://ziglang.org/) All your codebase are belong to us!
         - Maybe do some nice compression of the data structure?
     - [ ] [<sub><sub><img src="https://raw.githubusercontent.com/Validark/Validark/master/python.svg" alt="Python" height="22"></sub></sub>](https://www.python.org/) I don't actually "know python" yet, but the constructs I need to write this library should be pretty trivial. 
     - [ ] [<sub><sub><img src="https://raw.githubusercontent.com/Validark/Validark/master/go.svg" alt="Go" height="18"></sub></sub>](https://go.dev/) fast!
    - [ ] [<sub><sub><img src="https://raw.githubusercontent.com/Validark/Validark/master/markdown.svg" alt="Markdown" height="18"></sub></sub>](https://www.markdownguide.org/) Make a table that displays the supported features for each version. More than likely, the initial implementation for many languages may not have [numeric compression](https://validark.github.io/DynSDT/#numeric_compression) initially.
